<?xml version="1.0" encoding="utf-8"?><Database Name="dLogging" Class="SupplierDataManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RoviaDev;Initial Catalog=dLogging;Integrated Security=True" SettingsObjectName="Tavisca.SupplierScheduledTask.DataAccessLayer.Properties.Settings" SettingsPropertyName="dLoggingConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spGetLogBasedOnCallType" Method="spGetLogBasedOnCallType">
    <Parameter Name="CallType" Parameter="callType" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="SupplierId" Parameter="supplierId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TimeDiff" Parameter="timeDiff" Type="System.Int32" DbType="Int" />
    <Parameter Name="SupplierName" Parameter="supplierName" Type="System.String" DbType="NVarChar(64)" />
    <ElementType Name="spGetLogBasedOnCallTypeResult">
      <Column Name="ProviderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Calltype" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Success" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Failure" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PerSuccess" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PerFailure" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>