//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierScheduledTask.Vexiere.NotificationService
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationContext", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class ApplicationContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] AdditionalDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "KeyValuePair", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class KeyValuePair : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Message", Namespace = "http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.MailMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.TemplateMessage))]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BCCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus StatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.Attachment[] AttachmentsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.DateTime SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public SupplierScheduledTask.Vexiere.NotificationService.Attachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MailMessage", Namespace = "http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.SerializableAttribute()]
    public partial class MailMessage : SupplierScheduledTask.Vexiere.NotificationService.Message
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemplateMessage", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class TemplateMessage : SupplierScheduledTask.Vexiere.NotificationService.Message
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] TemplateAttributesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] TemplateAttributes
        {
            get
            {
                return this.TemplateAttributesField;
            }
            set
            {
                this.TemplateAttributesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName
        {
            get
            {
                return this.TemplateNameField;
            }
            set
            {
                this.TemplateNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DeliveryStatus", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public enum DeliveryStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentSuccessful = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureRetry = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Attachment", Namespace = "http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtensionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachmentFileField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public byte[] AttachmentFile
        {
            get
            {
                return this.AttachmentFileField;
            }
            set
            {
                this.AttachmentFileField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Criteria", Namespace = "http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.SerializableAttribute()]
    public partial class Criteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DatesSpecifiedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FromField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BCCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] MessageIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.PageDetail PageDetailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.TagOperation TagOperationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyTagFilterField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus StatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DatesSpecified
        {
            get
            {
                return this.DatesSpecifiedField;
            }
            set
            {
                this.DatesSpecifiedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public string[] From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public System.Guid[] MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public SupplierScheduledTask.Vexiere.NotificationService.PageDetail PageDetail
        {
            get
            {
                return this.PageDetailField;
            }
            set
            {
                this.PageDetailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public SupplierScheduledTask.Vexiere.NotificationService.TagOperation TagOperation
        {
            get
            {
                return this.TagOperationField;
            }
            set
            {
                this.TagOperationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public bool ApplyTagFilter
        {
            get
            {
                return this.ApplyTagFilterField;
            }
            set
            {
                this.ApplyTagFilterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PageDetail", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class PageDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TagOperation", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public enum TagOperation : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Or = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        And = 1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageList", Namespace = "http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.SerializableAttribute()]
    public partial class MessageList : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.Message[] MessagesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.PagingInfo PagingInfoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.Message[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.PagingInfo PagingInfo
        {
            get
            {
                return this.PagingInfoField;
            }
            set
            {
                this.PagingInfoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PagingInfo", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalResultField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResult
        {
            get
            {
                return this.TotalResultField;
            }
            set
            {
                this.TotalResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageInfoList", Namespace = "http://Tavisca.NotificationService.DataContracts/2008/11")]
    [System.SerializableAttribute()]
    public partial class MessageInfoList : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.MessageInfo[] MessagesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.PagingInfo PagingInfoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.MessageInfo[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.PagingInfo PagingInfo
        {
            get
            {
                return this.PagingInfoField;
            }
            set
            {
                this.PagingInfoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageInfo", Namespace = "http://Tavisca.NotificationService.DataContracts/2008/11")]
    [System.SerializableAttribute()]
    public partial class MessageInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BCCField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus StatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public SupplierScheduledTask.Vexiere.NotificationService.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.DateTime SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TagList", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class TagList : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Template", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class Template : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] AdditionalDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.TemplateTag[] TagsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.KeyValuePair[] AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.TemplateTag[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemplateTag", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class TemplateTag : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemplateList", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class TemplateList : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SupplierScheduledTask.Vexiere.NotificationService.TemplateInfo[] TemplatesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SupplierScheduledTask.Vexiere.NotificationService.TemplateInfo[] Templates
        {
            get
            {
                return this.TemplatesField;
            }
            set
            {
                this.TemplatesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemplateInfo", Namespace = "http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class TemplateInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ErrorIdField;

        private string ErrorMessageField;

        private System.Guid CorrelationIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ErrorId
        {
            get
            {
                return this.ErrorIdField;
            }
            set
            {
                this.ErrorIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Guid CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://Tavisca.NotificationService.ServiceContracts/2007/11", ConfigurationName = "SupplierScheduledTask.Vexiere.NotificationService.IMail")]
    public interface IMail
    {

        [System.ServiceModel.OperationContractAttribute(Action = "SendMail", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/SendMailRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/SendMailDefault" +
            "FaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Guid SendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Message message);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "SendMail", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/SendMailRespons" +
            "e")]
        System.IAsyncResult BeginSendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Message message, System.AsyncCallback callback, object asyncState);

        System.Guid EndSendMail(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetMails", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsDefault" +
            "FaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.MessageList GetMails(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetMails", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsRespons" +
            "e")]
        System.IAsyncResult BeginGetMails(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.MessageList EndGetMails(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetMailsInfo", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsInfoRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsInfoDef" +
            "aultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.MessageInfoList GetMailsInfo(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetMailsInfo", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsInfoRes" +
            "ponse")]
        System.IAsyncResult BeginGetMailsInfo(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.MessageInfoList EndGetMailsInfo(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetTags", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTagsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTagsDefaultF" +
            "aultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.TagList GetTags(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetTags", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTagsResponse" +
            "")]
        System.IAsyncResult BeginGetTags(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.TagList EndGetTags(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "ResendMail", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/ResendMailRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/ResendMailDefau" +
            "ltFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        void ResendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.Guid id);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "ResendMail", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/ResendMailRespo" +
            "nse")]
        System.IAsyncResult BeginResendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.Guid id, System.AsyncCallback callback, object asyncState);

        void EndResendMail(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "CreateTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/CreateTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/CreateTemplateD" +
            "efaultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        void CreateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Template template);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "CreateTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/CreateTemplateR" +
            "esponse")]
        System.IAsyncResult BeginCreateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Template template, System.AsyncCallback callback, object asyncState);

        void EndCreateTemplate(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "DeleteTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/DeleteTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/DeleteTemplateD" +
            "efaultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        void DeleteTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "DeleteTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/DeleteTemplateR" +
            "esponse")]
        System.IAsyncResult BeginDeleteTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, System.AsyncCallback callback, object asyncState);

        void EndDeleteTemplate(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "UpdateTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/UpdateTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/UpdateTemplateD" +
            "efaultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        void UpdateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, SupplierScheduledTask.Vexiere.NotificationService.Template template);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "UpdateTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/UpdateTemplateR" +
            "esponse")]
        System.IAsyncResult BeginUpdateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, SupplierScheduledTask.Vexiere.NotificationService.Template template, System.AsyncCallback callback, object asyncState);

        void EndUpdateTemplate(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplateResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplateDefa" +
            "ultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.Template GetTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetTemplate", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplateResp" +
            "onse")]
        System.IAsyncResult BeginGetTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.Template EndGetTemplate(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetTemplates", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplatesRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplatesDef" +
            "aultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.TemplateList GetTemplates(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetTemplates", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplatesRes" +
            "ponse")]
        System.IAsyncResult BeginGetTemplates(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.TemplateList EndGetTemplates(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "GetResolvedMessage", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetResolvedMess" +
            "ageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SupplierScheduledTask.Vexiere.NotificationService.DefaultFaultContract), Action = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetResolvedMess" +
            "ageDefaultFaultContractFault", Name = "DefaultFaultContract", Namespace = "http://Tavisca.NotificationService.FaultContracts/2007/11")]
        SupplierScheduledTask.Vexiere.NotificationService.MailMessage GetResolvedMessage(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.TemplateMessage templateMessage);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "GetResolvedMessage", ReplyAction = "http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetResolvedMess" +
            "ageResponse")]
        System.IAsyncResult BeginGetResolvedMessage(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.TemplateMessage templateMessage, System.AsyncCallback callback, object asyncState);

        SupplierScheduledTask.Vexiere.NotificationService.MailMessage EndGetResolvedMessage(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailChannel : SupplierScheduledTask.Vexiere.NotificationService.IMail, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailClient : System.ServiceModel.ClientBase<SupplierScheduledTask.Vexiere.NotificationService.IMail>, SupplierScheduledTask.Vexiere.NotificationService.IMail
    {

        public MailClient()
        {
        }

        public MailClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public MailClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Guid SendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Message message)
        {
            return base.Channel.SendMail(applicationContext, message);
        }

        public System.IAsyncResult BeginSendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Message message, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSendMail(applicationContext, message, callback, asyncState);
        }

        public System.Guid EndSendMail(System.IAsyncResult result)
        {
            return base.Channel.EndSendMail(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MessageList GetMails(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria)
        {
            return base.Channel.GetMails(applicationContext, criteria);
        }

        public System.IAsyncResult BeginGetMails(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetMails(applicationContext, criteria, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MessageList EndGetMails(System.IAsyncResult result)
        {
            return base.Channel.EndGetMails(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MessageInfoList GetMailsInfo(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria)
        {
            return base.Channel.GetMailsInfo(applicationContext, criteria);
        }

        public System.IAsyncResult BeginGetMailsInfo(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Criteria criteria, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetMailsInfo(applicationContext, criteria, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MessageInfoList EndGetMailsInfo(System.IAsyncResult result)
        {
            return base.Channel.EndGetMailsInfo(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.TagList GetTags(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext)
        {
            return base.Channel.GetTags(applicationContext);
        }

        public System.IAsyncResult BeginGetTags(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetTags(applicationContext, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.TagList EndGetTags(System.IAsyncResult result)
        {
            return base.Channel.EndGetTags(result);
        }

        public void ResendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.Guid id)
        {
            base.Channel.ResendMail(applicationContext, id);
        }

        public System.IAsyncResult BeginResendMail(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.Guid id, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginResendMail(applicationContext, id, callback, asyncState);
        }

        public void EndResendMail(System.IAsyncResult result)
        {
            base.Channel.EndResendMail(result);
        }

        public void CreateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Template template)
        {
            base.Channel.CreateTemplate(applicationContext, template);
        }

        public System.IAsyncResult BeginCreateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.Template template, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginCreateTemplate(applicationContext, template, callback, asyncState);
        }

        public void EndCreateTemplate(System.IAsyncResult result)
        {
            base.Channel.EndCreateTemplate(result);
        }

        public void DeleteTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName)
        {
            base.Channel.DeleteTemplate(applicationContext, templateName);
        }

        public System.IAsyncResult BeginDeleteTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDeleteTemplate(applicationContext, templateName, callback, asyncState);
        }

        public void EndDeleteTemplate(System.IAsyncResult result)
        {
            base.Channel.EndDeleteTemplate(result);
        }

        public void UpdateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, SupplierScheduledTask.Vexiere.NotificationService.Template template)
        {
            base.Channel.UpdateTemplate(applicationContext, templateName, template);
        }

        public System.IAsyncResult BeginUpdateTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, SupplierScheduledTask.Vexiere.NotificationService.Template template, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginUpdateTemplate(applicationContext, templateName, template, callback, asyncState);
        }

        public void EndUpdateTemplate(System.IAsyncResult result)
        {
            base.Channel.EndUpdateTemplate(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.Template GetTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName)
        {
            return base.Channel.GetTemplate(applicationContext, templateName);
        }

        public System.IAsyncResult BeginGetTemplate(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, string templateName, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetTemplate(applicationContext, templateName, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.Template EndGetTemplate(System.IAsyncResult result)
        {
            return base.Channel.EndGetTemplate(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.TemplateList GetTemplates(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext)
        {
            return base.Channel.GetTemplates(applicationContext);
        }

        public System.IAsyncResult BeginGetTemplates(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetTemplates(applicationContext, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.TemplateList EndGetTemplates(System.IAsyncResult result)
        {
            return base.Channel.EndGetTemplates(result);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MailMessage GetResolvedMessage(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.TemplateMessage templateMessage)
        {
            return base.Channel.GetResolvedMessage(applicationContext, templateMessage);
        }

        public System.IAsyncResult BeginGetResolvedMessage(SupplierScheduledTask.Vexiere.NotificationService.ApplicationContext applicationContext, SupplierScheduledTask.Vexiere.NotificationService.TemplateMessage templateMessage, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetResolvedMessage(applicationContext, templateMessage, callback, asyncState);
        }

        public SupplierScheduledTask.Vexiere.NotificationService.MailMessage EndGetResolvedMessage(System.IAsyncResult result)
        {
            return base.Channel.EndGetResolvedMessage(result);
        }
    }
}
